#!/bin/bash
# CCPSA Image Download Script
# Downloads all provider photos and site images for self-hosting
# Run this from the ccpsa-site folder: bash download-images.sh

echo "Creating image directories..."
mkdir -p images/providers
mkdir -p images/site

echo ""
echo "Downloading 52 provider headshots from WordPress..."
echo "=================================================="

WP="https://www.critcaremd.com/wp-content/uploads"

# Provider headshots - downloading with clean filenames
curl -sL "$WP/2022/07/Ahn-Brian-Headshot2-259x300.jpg" -o "images/providers/ahn-brian.jpg" && echo "  Downloaded: Brian Ahn"
curl -sL "$WP/2019/09/Bailey-Kolene-Headshot2-e1569512676267-259x300.jpg" -o "images/providers/bailey-kolene.jpg" && echo "  Downloaded: Kolene Bailey"
curl -sL "$WP/2022/10/Barnhill3-259x300.jpg" -o "images/providers/barnhill-serena.jpg" && echo "  Downloaded: Serena Barnhill"
curl -sL "$WP/2023/03/Photo_BensonAlex_Portrait-3-259x300.jpg" -o "images/providers/benson-alexander.jpg" && echo "  Downloaded: Alexander Benson"
curl -sL "$WP/2022/10/Biehl-Jason-Headshot2-259x300.jpg" -o "images/providers/biehl-jason.jpg" && echo "  Downloaded: Jason Biehl"
curl -sL "$WP/2024/11/Blount-Jacob-headshot3-259x300.jpg" -o "images/providers/blount-jacob.jpg" && echo "  Downloaded: Jacob Blount"
curl -sL "$WP/2017/06/darren-259x300.png" -o "images/providers/boe-darren.png" && echo "  Downloaded: Darren Boe"
curl -sL "$WP/2024/10/Bowman-Photo-259x300.jpg" -o "images/providers/bowman-amelia.jpg" && echo "  Downloaded: Amelia Bowman"
curl -sL "$WP/2017/06/dickinson.jpg" -o "images/providers/dickinson-matthew.jpg" && echo "  Downloaded: Matthew Dickinson"
curl -sL "$WP/2022/06/Florian-Headshot2.jpg" -o "images/providers/florian-jana.jpg" && echo "  Downloaded: Jana Florian"
curl -sL "$WP/2024/04/Gonzales-Headshot.jpg" -o "images/providers/gonzales-mia.jpg" && echo "  Downloaded: Mia Gonzales"
curl -sL "$WP/2017/06/M.Hay_.p.jpg" -o "images/providers/hay-margaret.jpg" && echo "  Downloaded: Margaret Hay"
curl -sL "$WP/2022/07/Headshot-Horn-Emily.jpg" -o "images/providers/horn-emily.jpg" && echo "  Downloaded: Emily Horn"
curl -sL "$WP/2017/06/khalifah.jpg" -o "images/providers/khalifah-anthony.jpg" && echo "  Downloaded: Anthony Khalifah"
curl -sL "$WP/2025/09/Catherine-Kim-Headshot2.jpg" -o "images/providers/kim-catherine.jpg" && echo "  Downloaded: Catherine Kim"
curl -sL "$WP/2022/07/Lee-Josh-Headshot-1.jpg" -o "images/providers/lee-josh.jpg" && echo "  Downloaded: Josh Lee"
curl -sL "$WP/2023/03/Nate-Little-MD_.jpg" -o "images/providers/little-nathaniel.jpg" && echo "  Downloaded: Nathaniel Little"
curl -sL "$WP/2022/10/Macht-Madison-Headshot2.jpg" -o "images/providers/macht-madison.jpg" && echo "  Downloaded: Madison Macht"
curl -sL "$WP/2024/03/McPherson-Headshot-scaled.jpg" -o "images/providers/mcpherson-katie.jpg" && echo "  Downloaded: Katie McPherson"
curl -sL "$WP/2021/03/Metkus-3-1.jpg" -o "images/providers/metkus-james.jpg" && echo "  Downloaded: James Metkus"
curl -sL "$WP/2023/06/Miller-Jen-Photo.jpeg" -o "images/providers/miller-jen.jpeg" && echo "  Downloaded: Jen Miller"
curl -sL "$WP/2021/09/mytinger_headshot.png" -o "images/providers/mytinger-andrea.png" && echo "  Downloaded: Andrea Mytinger"
curl -sL "$WP/2017/06/aaron.jpg" -o "images/providers/nadon-aaron.jpg" && echo "  Downloaded: Aaron Nadon"
curl -sL "$WP/2025/09/Julia-Newman2.jpg" -o "images/providers/newman-julia.jpg" && echo "  Downloaded: Julia Newman"
curl -sL "$WP/2024/10/Pachecco-Navarro2-.jpg" -o "images/providers/pacheco-navarro-ana.jpg" && echo "  Downloaded: Ana Pacheco-Navarro"
curl -sL "$WP/2017/06/riley.jpg" -o "images/providers/riley-peter.jpg" && echo "  Downloaded: Peter Riley"
curl -sL "$WP/2017/06/alex-smart.jpg" -o "images/providers/smart-alexandra.jpg" && echo "  Downloaded: Alexandra Smart"
curl -sL "$WP/2017/06/Headshot-Stramel.jpg" -o "images/providers/stramel-eric.jpg" && echo "  Downloaded: Eric Stramel"
curl -sL "$WP/2020/09/Ryan.Sullivan-cropped.jpg" -o "images/providers/sullivan-ryan.jpg" && echo "  Downloaded: Ryan Sullivan"
curl -sL "$WP/2019/02/sutarik.jpg" -o "images/providers/sutarik-julie.jpg" && echo "  Downloaded: Julie Sutarik"
curl -sL "$WP/2021/04/Taylor-Jen-Headshot.jpg" -o "images/providers/taylor-jennifer.jpg" && echo "  Downloaded: Jennifer Taylor"
curl -sL "$WP/2022/07/Thomas-Nadler-Headshot.jpg" -o "images/providers/thomas-nadler-samantha.jpg" && echo "  Downloaded: Samantha Thomas-Nadler"
curl -sL "$WP/2024/11/Titone-2024.2-scaled.jpg" -o "images/providers/titone-dominic.jpg" && echo "  Downloaded: Dominic Titone"
curl -sL "$WP/2019/07/Waasphoto.jpg" -o "images/providers/waas-andrew.jpg" && echo "  Downloaded: Andrew Waas"
curl -sL "$WP/2022/10/Wink-Headshot2-1-scaled.jpg" -o "images/providers/wink-jennifer.jpg" && echo "  Downloaded: Jennifer Wink"
curl -sL "$WP/2017/06/Headshot-Elmasri.jpg" -o "images/providers/elmasri-mary.jpg" && echo "  Downloaded: Mary Elmasri"
curl -sL "$WP/2022/10/Anne-Reihman-01.jpg" -o "images/providers/reihman-anne.jpg" && echo "  Downloaded: Anne Reihman"
curl -sL "$WP/2017/06/bost.jpg" -o "images/providers/bost-tom.jpg" && echo "  Downloaded: Tom Bost"
curl -sL "$WP/2023/09/Anderson-Pleiss-scaled.jpg" -o "images/providers/anderson-pleiss-amanda.jpg" && echo "  Downloaded: Amanda Anderson-Pleiss"
curl -sL "$WP/2021/01/Headshot-Ludlow-Laura.jpg" -o "images/providers/ludlow-laura.jpg" && echo "  Downloaded: Laura Ludlow"
curl -sL "$WP/2022/04/Savolt-Headshot.jpg" -o "images/providers/savolt-amanda.jpg" && echo "  Downloaded: Amanda Savolt"
curl -sL "$WP/2022/07/CStrappini-scaled.jpg" -o "images/providers/strappini-carly.jpg" && echo "  Downloaded: Carly Strappini"
curl -sL "$WP/2019/02/Sarah-Mateer-e1552418924575.jpg" -o "images/providers/mateer-sarah.jpg" && echo "  Downloaded: Sarah Mateer"
curl -sL "$WP/2025/08/Ronnenbaum2.jpeg" -o "images/providers/yount-emily.jpeg" && echo "  Downloaded: Emily Yount"
curl -sL "$WP/2021/06/Batton-Alisa-Webiste-Headshot-rotated.jpg" -o "images/providers/batton-alisa.jpg" && echo "  Downloaded: Alisa Batton"
curl -sL "$WP/2021/06/E7699D40-22CA-4549-B6FC-98C86D9FF111.jpeg" -o "images/providers/brown-erica.jpeg" && echo "  Downloaded: Erica Brown"
curl -sL "$WP/2021/01/Cheri-Hughes.jpg" -o "images/providers/hughes-cheri.jpg" && echo "  Downloaded: Cheri Hughes"
curl -sL "$WP/2021/06/Phares-Carly-Headshot-updated-1-scaled.jpg" -o "images/providers/phares-carly.jpg" && echo "  Downloaded: Carly Phares"
curl -sL "$WP/2025/09/Turnbaugh.jpg" -o "images/providers/turnbaugh-nicole.jpg" && echo "  Downloaded: Nicole Turnbaugh"
curl -sL "$WP/2017/06/dennen.jpg" -o "images/providers/dennen-paula.jpg" && echo "  Downloaded: Paula Dennen"
curl -sL "$WP/2021/04/Roscoe-Danielle-Headshot.jpg" -o "images/providers/greco-danielle.jpg" && echo "  Downloaded: Danielle Greco"
curl -sL "$WP/2025/09/Schoenrock-Headshot2-1-scaled.jpg" -o "images/providers/schoenrock-amber.jpg" && echo "  Downloaded: Amber Schoenrock"

echo ""
echo "Downloading 4 site images from Vercel blob storage..."
echo "=================================================="
curl -sL "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-37k9ir4fVsutZ3zB6sVEWXtdGrqMSN.png" -o "images/site/ccpsa-logo.png" && echo "  Downloaded: CCPSA Logo"
curl -sL "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/CritCare-78-u2A5RCvTkbK81e4WXWhrtzFZ3SaKOH.jpg" -o "images/site/hero-team.jpg" && echo "  Downloaded: Hero team photo"
curl -sL "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/CritCare-57-1-DZQC9aqHinfkq1TIwq8Cu4LpxRWRln.jpg" -o "images/site/hero-consulting.jpg" && echo "  Downloaded: Consulting photo"
curl -sL "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/CritCare-163-iQUaBI8RYVHVa6TZThibjHWmQgV9ia.jpg" -o "images/site/hero-data.jpg" && echo "  Downloaded: Data review photo"

echo ""
echo "=================================================="
echo "Download complete!"
echo ""
PROVIDER_COUNT=$(ls -1 images/providers/ 2>/dev/null | wc -l)
SITE_COUNT=$(ls -1 images/site/ 2>/dev/null | wc -l)
echo "Provider photos: $PROVIDER_COUNT downloaded"
echo "Site images: $SITE_COUNT downloaded"
echo ""
echo "Total size:"
du -sh images/
echo ""
echo "You can now upload the 'images' folder to your GitHub repository."
